### ISSUE TITLE
html injection

### ISSUE THREAD

**Issue by jdanyow** [cristianbote/hnpwa-vanilla#9]
https://github.com/cristianbote/hnpwa-vanilla/blob/aca303b930194c4394c0f3cf088dc5e94206ee8d/src/core/dom-api.js#L18-L25

`innerHTML` might be an issue if the title of the post is something like:

> `PWA suffers <em onmouseover="alert('hi')"> html injection attack!`

**Comment by cristianbote** [comment]
Hey @jdanyow, thanks for reaching out!

Indeed! This is highly injectable 😃. Keep in mind though, this method is used for creating the content inside of an _element_.

Initially I wanted to reply an say that the `dom-api` should not bother with sanitizing, because you'd want to pass in `onclick` listeners, but that would be wrong 😄. You should pass them via the attributes.

```js
// Bad
span(null, 'PWA suffers <em onmouseover="alert('hi')"> html injection attack!');

// Good
span(null, [
  'PWA suffers',
  em({ onmouseover: () => alert('hi'), ''),
  'html injection attack!'
]);
```
I'll get to it and fix it.

Thanks again for your feedback! Much appreciate it!

**Comment by jdanyow** [comment]
The "on" example I provided was one of [many](https://deadliestwebattacks.com/html-injection-quick-reference/).  To truly fix this I think you'll need to stop assigning `innerHTML` and switch to using `textContent` for the post title, etc.

Nice work on the PWA by the way 👍 I'm only opening this issue because this app will be a good example for folks once this XSS/HTML-injection hole is patched.

**Comment by cristianbote** [comment]
Oh, ok, I think I understand your concern, now. Yeah, I don't think we'll ever run into that sort of injection, since all the content is based on the _real_ hackernews api content, if that content will ever come with XSS in it, we'll have a bigger problem in our hands.
Take a look at this response: https://node-hnapi.herokuapp.com/item/15989148. As you can see, every field that has data, is escaped. And that is by design.

Now, having the content escaped and dumped via `innerHTML`, makes for a better reading experience in the form that was original intended.

Also `textContent` does just that, sets the _string_ based content; no parsing for html bodies. That would mean to clean-up the content for every tag and display a _slate_ version of the content.

I understand your concern but I think it's just not needed here. The only _client_ based input is the page number, which is parsed at runtime to be an integer.

Please let me know if there's more to it. I tried to be pretty accurate security wise, but I don't see any more issues, that could be on the client and could be exploited.

Once again, thank you! Really helpful 😃

**Comment by jdanyow** [comment]
gotcha- I didn't realize the title property was html-escaped.
